@rootURL = http://localhost:5168

GET {{rootURL}}/wallets/
Accept: application/json

###
GET {{rootURL}}/wallets/tx101
Accept: application/json

###

GET {{rootURL}}/wallets/undefined
Accept: application/json

###
POST {{rootURL}}/wallets/7e178edd-4aa0-4f6c-9c8b-b3b901e10d1a/credit
Content-Type: application/json

{
    "transactionId": "tx102",
    "coins": 1000
}

###

POST {{rootURL}}/wallets/7e178edd-4aa0-4f6c-9c8b-b3b901e10d1a/debit
Content-Type: application/json

{
    "transactionId": "tx123",
    "coins": 2000
}

###

POST {{rootURL}}/wallets/7e178edd-4aa0-4f6c-9c8b-b3b901e10d1a/debit
Content-Type: application/json

{
    "transactionId": "tx124",
    "coins": 500
}

###
PUT {{rootURL}}/wallets/refresh
Content-Type: application/json
