// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WalletAPI.Data;

#nullable disable

namespace WalletAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901102556_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalletAPI.models.Wallet", b =>
                {
                    b.Property<string>("walletId")
                        .HasColumnType("text");

                    b.Property<int>("coins")
                        .HasColumnType("integer");

                    b.Property<string>("transactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.HasKey("walletId");

                    b.ToTable("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
